package com.example.myapplication;

public enum PopUpType {
    DELETE_PLAYER,
    ARCHIVE_PLAYER,
    UNARCHIVE_PLAYER,

    DELETE_TOURNAMENT,
    ACTIVATE_TOURNAMENT,
    DEACTIVATE_TOURNAMENT,

    DELETE_TEAM,

    DELETE_MATCH,
    DELETE_EVERY_MATCH,
}
